# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-02 03:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.CharField(max_length=200)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_comments.ArticleInformation')),
            ],
        ),
    ]
