# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-02 04:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_comments', '0002_voters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlescore',
            old_name='article_id',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='articlevotes',
            old_name='article_id',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='voters',
            old_name='article_id',
            new_name='article',
        ),
    ]
