# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-14 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fishing_books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentor_name', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Storages',
            new_name='Storage',
        ),
        migrations.AddField(
            model_name='comment',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishing_books.Storage'),
        ),
    ]
